### ISSUE TITLE
Running examples gives input_size error 

### ISSUE THREAD

**Issue by alhussein-jamil** [facebookresearch/bc-irl#4]
I cloned the repository and installed python 3.7 as well as the requirements. 
whenever I try a given example :
 `python imitation_learning/run.py +bc_irl=pointmass`

I get the following error : 
`Error executing job with overrides: ['+bc_irl=pointmass']
Traceback (most recent call last):
  File "imitation_learning/run.py", line 128, in main
    updater.update(policy, storage_td, logger, envs=envs)
  File "/home/user/Downloads/bc-irl-main/imitation_learning/bcirl.py", line 166, in update
    self.inner_updater.update(dpolicy, rollouts, logger, diffopt)
  File "/home/user/Downloads/bc-irl-main/imitation_learning/policy_opt/ppo.py", line 75, in update
    last_value,
  File "/home/user/Downloads/bc-irl-main/imitation_learning/policy_opt/ppo.py", line 164, in compute_gae
    returns[:, step] = gae + value_preds[:, step].reshape(gae.shape)
RuntimeError: shape '[256, 256]' is invalid for input of size 256`

**Comment by alhussein-jamil** [comment]
I fixed that issue by modifying the following lines in PPO.py 
LINE 89: 
`                    ac_eval["log_prob"].view(-1, 1) - batch["sample_log_prob"]` becomes `                    ac_eval["log_prob"].view(-1, 1) - batch["sample_log_prob"].view(-1,1)`
LINE 159 : 
`               + self.gamma * next_val * masks[:, step]` becomes `                + self.gamma * next_val * masks[:, step].view(-1,1)`
LINE 162: 
`            gae = delta + self.gamma * self.gae_lambda * masks[:, step] * gae` becomes `            gae = delta + self.gamma * self.gae_lambda * masks[:, step].view(-1,1)  *  gae`

**Comment by ASzot** [comment]
Hello, I just pushed a fix for this. Please re-pull and re-install and it should be fixed.

**Comment by alhussein-jamil** [comment]
Perfect
